### PR TITLE
Optional theming to Android splash screen

### LINKED ISSUE #123: Can't convert to color: type=0x1
It seams that something is wrong in android.

react native: 0.47.2
android: 6.0.1

java.lang.UnsupportedOperationException: Can't convert to color: type=0x1
--
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423)
3 ......
4 Caused by:
5 java.lang.UnsupportedOperationException:Can't convert to color: type=0x1
6 android.content.res.TypedArray.getColor(TypedArray.java:453)
7 com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3779)
8 com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:3983)
9 com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:383)
10 android.app.Dialog.setContentView(Dialog.java:515)
11 org.devio.rn.splashscreen.SplashScreen$1.run(SplashScreen.java:32)
12 android.app.Activity.runOnUiThread(Activity.java:5573)
13 org.devio.rn.splashscreen.SplashScreen.show(SplashScreen.java:26)
14 org.devio.rn.splashscreen.SplashScreen.show(SplashScreen.java:47)
15 com.gf.mobile.clickeggs2.MainActivity.onCreate(MainActivity.java:27)

### PR DESCRIPTION
**Pull request by christophermark**
#102 had introduced a breaking change, where builds would fail if you didn't add a style definition for the status bar color.

This PR reverts those changes but introduces an alternative, backward-compatible method of setting custom status bar colors through theming. I've overloaded the `show` method, so you can choose to optionally include a style, or not include a style at all.

If you wanted to change the status bar color to a color `primary_dark ` in your `colors.xml` file, you'd create a style definition in your app, presumably in `styles.xml`:
```java
<style name="SplashScreenTheme" parent="SplashScreen_SplashTheme">
    <item name="colorPrimaryDark">@color/primary_dark</item>
</style>
```

Then you'd include this theme when showing the splash screen:
```java
SplashScreen.show(this, false, R.style.SplashScreenTheme);
```

## Related issues
Closes #123

### CODE REVIEW

File: android/src/main/java/org/devio/rn/splashscreen/SplashScreen.java [hunk 1]
```diff
@@ -14,21 +14,27 @@
...
         mActivity = new WeakReference<Activity>(activity);
         activity.runOnUiThread(new Runnable() {
             @Override
             public void run() {
                 if (!activity.isFinishing()) {
 
-                    mSplashDialog = new Dialog(activity, fullScreen ? R.style.SplashScreen_Fullscreen : R.style.SplashScreen_SplashTheme);
+                    mSplashDialog = new Dialog(
+                            activity,
+                            themeResId != NULL_ID ? themeResId
```
Comment (ArmandoAssuncao) [inline android/src/main/java/org/devio/rn/splashscreen/SplashScreen.java]: it would be best to check if it is `fullScreen` first.

Comment (christophermark) [reply android/src/main/java/org/devio/rn/splashscreen/SplashScreen.java]: Actually, now that I'm thinking about it, there might be an even cleaner implementation here:


```java
// Not concerned with fullscreen anymore
public static void show(final Activity activity, final int themeResId) {
  ...
}

public static void show(Activity activity, boolean fullScreen) {
    int resourceId = fullScreen ? R.style.SplashScreen_Fullscreen : R.style.SplashScreen_SplashTheme;

    show(activity, resourceId);
}

```
